"use client";

import { ClipboardList, Lock, Pencil, Send, Trash2 } from "lucide-react";
import ExamStatusBadge from "./ExamStatusBadge";
import type { Exam } from "./types";

type ExamsListProps = {
  exams: Exam[];
  onEdit: (exam: Exam) => void;
  onPublish: (exam: Exam) => void;
  onLock: (exam: Exam) => void;
  onDelete: (exam: Exam) => void;
};

function ExamActions({ exam, onEdit, onPublish, onLock, onDelete }: { exam: Exam; onEdit: () => void; onPublish: () => void; onLock: () => void; onDelete: () => void }) {
  return <div className="flex shrink-0 gap-1"><button type="button" title={exam.is_locked ? "Locked — cannot edit" : "Edit exam"} disabled={exam.is_locked} onClick={onEdit} className="rounded-lg p-1.5 text-slate-400 transition-colors hover:bg-[#8B6DF2]/10 hover:text-[#8B6DF2] disabled:cursor-not-allowed disabled:opacity-30 dark:text-slate-500"><Pencil size={16} /></button>{!exam.is_published && !exam.is_locked && <button type="button" title="Publish exam" onClick={onPublish} className="rounded-lg p-1.5 text-slate-400 transition-colors hover:bg-emerald-500/10 hover:text-emerald-600 dark:text-slate-500 dark:hover:text-emerald-400"><Send size={16} /></button>}{exam.is_published && !exam.is_locked && <button type="button" title="Lock exam" onClick={onLock} className="rounded-lg p-1.5 text-slate-400 transition-colors hover:bg-red-500/10 hover:text-red-500 dark:text-slate-500"><Lock size={16} /></button>}<button type="button" title={exam.is_published || exam.is_locked ? "Only draft exams can be deleted" : "Delete exam"} disabled={exam.is_published || exam.is_locked} onClick={onDelete} className="rounded-lg p-1.5 text-slate-400 transition-colors hover:bg-red-500/10 hover:text-red-500 disabled:cursor-not-allowed disabled:opacity-30 dark:text-slate-500"><Trash2 size={16} /></button></div>;
}

export default function ExamsList({ exams, onEdit, onPublish, onLock, onDelete }: ExamsListProps) {
  return <>
    <div className="grid gap-3 sm:hidden">{exams.map((exam) => <article key={exam.id} className="rounded-xl border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-white/[0.03]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-900 dark:text-slate-50">{exam.name}</p><div className="mt-2 flex flex-wrap items-center gap-2"><ExamStatusBadge exam={exam} /><span className="rounded-md border border-violet-400/25 bg-violet-50 px-2 py-1 text-xs font-semibold text-violet-600 dark:border-violet-400/20 dark:bg-violet-500/10 dark:text-violet-400">{(exam.weightage * 100).toFixed(0)}% weight</span></div></div><ExamActions exam={exam} onEdit={() => onEdit(exam)} onPublish={() => onPublish(exam)} onLock={() => onLock(exam)} onDelete={() => onDelete(exam)} /></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-slate-100 pt-3 text-xs dark:border-white/5"><div><p className="text-slate-400 dark:text-slate-500">Term</p><p className="mt-1 font-medium text-slate-700 dark:text-slate-200">{exam.term?.name ?? `Term #${exam.term_id}`}</p></div><div><p className="text-slate-400 dark:text-slate-500">Schedule</p><p className="mt-1 font-medium text-slate-700 dark:text-slate-200">{exam.start_date} → {exam.end_date}</p></div></div></article>)}</div>
    <div className="hidden overflow-x-auto rounded-xl border border-slate-200 dark:border-white/10 sm:block"><table className="w-full min-w-[850px] border-collapse text-left"><thead className="bg-slate-50 dark:bg-white/[0.03]"><tr>{["Exam Name", "Term", "Start Date", "End Date", "Weightage", "Status", "Actions"].map((heading) => <th key={heading} className="px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">{heading}</th>)}</tr></thead><tbody>{exams.map((exam) => <tr key={exam.id} className="border-t border-slate-100 transition-colors hover:bg-slate-50 dark:border-white/5 dark:hover:bg-white/[0.02]"><td className="px-4 py-3 text-sm font-semibold text-slate-900 dark:text-slate-100"><span className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg border border-[#8B6DF2]/20 bg-[#8B6DF2]/10"><ClipboardList size={15} className="text-[#8B6DF2]" /></span>{exam.name}</span></td><td className="px-4 py-3 text-sm text-slate-600 dark:text-slate-300">{exam.term?.name ?? `Term #${exam.term_id}`}</td><td className="px-4 py-3 text-sm text-slate-500 dark:text-slate-400">{exam.start_date}</td><td className="px-4 py-3 text-sm text-slate-500 dark:text-slate-400">{exam.end_date}</td><td className="px-4 py-3"><span className="rounded-md border border-violet-400/25 bg-violet-50 px-2 py-1 text-xs font-semibold text-violet-600 dark:border-violet-400/20 dark:bg-violet-500/10 dark:text-violet-400">{(exam.weightage * 100).toFixed(0)}%</span></td><td className="px-4 py-3"><ExamStatusBadge exam={exam} /></td><td className="px-4 py-3"><ExamActions exam={exam} onEdit={() => onEdit(exam)} onPublish={() => onPublish(exam)} onLock={() => onLock(exam)} onDelete={() => onDelete(exam)} /></td></tr>)}</tbody></table></div>
  </>;
}
