"use client";

import { Trash2 } from "lucide-react";
import { GradeBadge, ScoreBar } from "./ResultScore";
import type { ExamPaper, ExamResult } from "./types";

export default function StudentResultsList({ results, papers, onDelete }: { results: ExamResult[]; papers: ExamPaper[]; onDelete: (result: ExamResult) => void }) {
  return <><div className="grid gap-3 sm:hidden">{results.map((result) => { const paper = papers.find((item) => item.id === result.exam_paper_id); return <article key={result.id} className="rounded-xl border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-white/[0.03]"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-slate-900 dark:text-slate-50">{paper?.exam_name ?? `Exam #${result.exam_paper_id}`}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{paper?.subject_name ?? "Unknown subject"}</p></div><button type="button" title="Delete result" onClick={() => onDelete(result)} className="rounded-lg p-1.5 text-slate-400 transition-colors hover:bg-red-500/10 hover:text-red-500 dark:text-slate-500"><Trash2 size={16} /></button></div><div className="mt-4 flex items-center justify-between gap-3 border-t border-slate-100 pt-3 dark:border-white/5">{paper ? <ScoreBar obtained={result.obtained_marks} total={paper.total_marks} pass={paper.pass_marks} /> : <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">{result.obtained_marks}</span>}<div className="text-right"><GradeBadge grade={result.grade} /><p className="mt-1 text-xs font-semibold text-blue-600 dark:text-blue-400">GPA {result.gpa != null ? result.gpa.toFixed(2) : "—"}</p></div></div></article>; })}</div><div className="hidden overflow-x-auto rounded-xl border border-slate-200 dark:border-white/10 sm:block"><table className="w-full min-w-[720px] border-collapse text-left"><thead className="bg-slate-50 dark:bg-white/[0.03]"><tr>{["Exam", "Subject", "Marks", "Grade", "GPA", "Actions"].map((heading) => <th key={heading} className="px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">{heading}</th>)}</tr></thead><tbody>{results.map((result) => { const paper = papers.find((item) => item.id === result.exam_paper_id); return <tr key={result.id} className="border-t border-slate-100 transition-colors hover:bg-slate-50 dark:border-white/5 dark:hover:bg-white/[0.02]"><td className="px-4 py-3 text-sm font-semibold text-slate-900 dark:text-slate-100">{paper?.exam_name ?? `Exam #${result.exam_paper_id}`}</td><td className="px-4 py-3 text-sm text-slate-600 dark:text-slate-300">{paper?.subject_name ?? "—"}</td><td className="px-4 py-3">{paper ? <ScoreBar obtained={result.obtained_marks} total={paper.total_marks} pass={paper.pass_marks} /> : result.obtained_marks}</td><td className="px-4 py-3"><GradeBadge grade={result.grade} /></td><td className="px-4 py-3 text-sm font-semibold text-blue-600 dark:text-blue-400">{result.gpa != null ? result.gpa.toFixed(2) : "—"}</td><td className="px-4 py-3"><button type="button" title="Delete result" onClick={() => onDelete(result)} className="rounded-lg p-1.5 text-slate-400 transition-colors hover:bg-red-500/10 hover:text-red-500 dark:text-slate-500"><Trash2 size={16} /></button></td></tr>; })}</tbody></table></div></>;
}
