"""add_academic_session_id_to_classrooms

Revision ID: 5348a9a39237
Revises: 4b0e803c4461
Create Date: 2026-03-30 18:17:59.174974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5348a9a39237'
down_revision: Union[str, Sequence[str], None] = '4b0e803c4461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_classrooms_academic_session_id'), 'classrooms', type_='foreignkey')
    op.drop_column('classrooms', 'academic_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('academic_session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_classrooms_academic_session_id'), 'classrooms', 'academic_sessions', ['academic_session_id'], ['id'])
    # ### end Alembic commands ###
