"""fix_classroom_academic_session_relationship

Revision ID: eb76b062fdcf
Revises: 5348a9a39237
Create Date: 2026-03-30 18:25:05.484856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb76b062fdcf'
down_revision: Union[str, Sequence[str], None] = '5348a9a39237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('academic_year_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'classrooms', 'academic_sessions', ['academic_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.drop_column('classrooms', 'academic_year_id')
    # ### end Alembic commands ###
