"""add class_teacher_member_id to classrooms

Revision ID: 02ee81aec386
Revises: 86e4c61737c3
Create Date: 2026-03-01 11:56:12.731299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ee81aec386'
down_revision: Union[str, Sequence[str], None] = '86e4c61737c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_subjects', sa.Column('classroom_id', sa.Integer(), nullable=False))
    op.add_column('class_subjects', sa.Column('teacher_member_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_class_subject', 'class_subjects', ['classroom_id', 'subject_id'])
    op.drop_constraint(op.f('class_subjects_class_id_fkey'), 'class_subjects', type_='foreignkey')
    op.create_foreign_key(None, 'class_subjects', 'organization_members', ['teacher_member_id'], ['id'])
    op.create_foreign_key(None, 'class_subjects', 'classrooms', ['classroom_id'], ['id'])
    op.drop_column('class_subjects', 'class_id')
    op.add_column('classrooms', sa.Column('class_teacher_member_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('classrooms_teacher_id_fkey'), 'classrooms', type_='foreignkey')
    op.create_foreign_key(None, 'classrooms', 'organization_members', ['class_teacher_member_id'], ['id'])
    op.drop_column('classrooms', 'teacher_id')
    op.add_column('exam_papers', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('unique_exam_paper'), 'exam_papers', type_='unique')
    op.create_unique_constraint('unique_exam_paper', 'exam_papers', ['exam_id', 'classroom_id', 'subject_id'])
    op.drop_constraint(op.f('exam_papers_class_id_fkey'), 'exam_papers', type_='foreignkey')
    op.create_foreign_key(None, 'exam_papers', 'classrooms', ['classroom_id'], ['id'])
    op.drop_column('exam_papers', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_papers', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exam_papers', type_='foreignkey')
    op.create_foreign_key(op.f('exam_papers_class_id_fkey'), 'exam_papers', 'classrooms', ['class_id'], ['id'])
    op.drop_constraint('unique_exam_paper', 'exam_papers', type_='unique')
    op.create_unique_constraint(op.f('unique_exam_paper'), 'exam_papers', ['exam_id', 'class_id', 'subject_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('exam_papers', 'classroom_id')
    op.add_column('classrooms', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.create_foreign_key(op.f('classrooms_teacher_id_fkey'), 'classrooms', 'users', ['teacher_id'], ['id'])
    op.drop_column('classrooms', 'class_teacher_member_id')
    op.add_column('class_subjects', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.drop_constraint(None, 'class_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('class_subjects_class_id_fkey'), 'class_subjects', 'classrooms', ['class_id'], ['id'])
    op.drop_constraint('uq_class_subject', 'class_subjects', type_='unique')
    op.drop_column('class_subjects', 'teacher_member_id')
    op.drop_column('class_subjects', 'classroom_id')
    # ### end Alembic commands ###
