"""update student table

Revision ID: 5c4df91298bd
Revises: 02ee81aec386
Create Date: 2026-03-02 00:11:30.092162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4df91298bd'
down_revision: Union[str, Sequence[str], None] = '02ee81aec386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_enrollments', sa.Column('roll_number', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('admission_no', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('admission_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('father_name', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('father_phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('mother_name', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('guardian_name', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('guardian_phone', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint('uq_student_admission_per_org', 'students', ['organization_id', 'admission_no'])
    op.drop_column('students', 'parent')
    op.drop_column('students', 'name')
    op.drop_column('students', 'roll')
    op.drop_column('students', 'contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('contact', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('roll', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('parent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('uq_student_admission_per_org', 'students', type_='unique')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'guardian_phone')
    op.drop_column('students', 'guardian_name')
    op.drop_column('students', 'mother_name')
    op.drop_column('students', 'father_phone')
    op.drop_column('students', 'father_name')
    op.drop_column('students', 'address')
    op.drop_column('students', 'email')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'admission_date')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'gender')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    op.drop_column('students', 'admission_no')
    op.drop_column('student_enrollments', 'roll_number')
    # ### end Alembic commands ###
