"""add session_id to expense table

Revision ID: 5ff1981743d8
Revises: a804b28244c2
Create Date: 2026-03-12 10:17:57.146003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff1981743d8'
down_revision: Union[str, Sequence[str], None] = 'a804b28244c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('academic_year_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'academic_sessions', ['academic_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'academic_year_id')
    # ### end Alembic commands ###
