"""add sesison_id to staffsalary table

Revision ID: 73808361ffe4
Revises: 8992114fef3a
Create Date: 2026-03-12 12:18:39.292207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73808361ffe4'
down_revision: Union[str, Sequence[str], None] = '8992114fef3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_payments', sa.Column('session_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'salary_payments', 'academic_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary_payments', type_='foreignkey')
    op.drop_column('salary_payments', 'session_id')
    # ### end Alembic commands ###
