"""add teacher_salaries and salary_payment tables

Revision ID: 7a491c950ad1
Revises: cb0b221078ae
Create Date: 2026-03-08 11:11:17.970394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a491c950ad1'
down_revision: Union[str, Sequence[str], None] = 'cb0b221078ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('teacher_member_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_frequency', sa.String(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['teacher_member_id'], ['organization_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_member_id', 'effective_from', name='uq_teacher_salary_effective_from')
    )
    op.create_index(op.f('ix_teacher_salaries_id'), 'teacher_salaries', ['id'], unique=False)
    op.create_table('salary_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('teacher_member_id', sa.Integer(), nullable=False),
    sa.Column('salary_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['salary_id'], ['teacher_salaries.id'], ),
    sa.ForeignKeyConstraint(['teacher_member_id'], ['organization_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_member_id', 'month', 'year', name='uq_teacher_salary_month')
    )
    op.create_index(op.f('ix_salary_payments_id'), 'salary_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_payments_id'), table_name='salary_payments')
    op.drop_table('salary_payments')
    op.drop_index(op.f('ix_teacher_salaries_id'), table_name='teacher_salaries')
    op.drop_table('teacher_salaries')
    # ### end Alembic commands ###
