"""add discount to student enrollment

Revision ID: 86e4c61737c3
Revises: c52abd3d09e8
Create Date: 2026-02-28 18:03:52.959586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e4c61737c3'
down_revision: Union[str, Sequence[str], None] = 'c52abd3d09e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_enrollments', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.drop_column('students', 'discount_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('discount_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('student_enrollments', 'discount_percent')
    # ### end Alembic commands ###
