"""rename academic_year_id to  session_id to attendance table

Revision ID: 8992114fef3a
Revises: 9fc6fd3648a2
Create Date: 2026-03-12 11:00:32.602009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8992114fef3a'
down_revision: Union[str, Sequence[str], None] = '9fc6fd3648a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('session_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attendances', 'academic_sessions', ['session_id'], ['id'])
    op.drop_constraint(op.f('classrooms_academic_year_id_fkey'), 'classrooms', type_='foreignkey')
    op.drop_column('classrooms', 'academic_year_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('academic_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('classrooms_academic_year_id_fkey'), 'classrooms', 'academic_sessions', ['academic_year_id'], ['id'])
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'session_id')
    # ### end Alembic commands ###
