"""Create staff_salaries and salary_payments

Revision ID: a804b28244c2
Revises: cb0b221078ae
Create Date: 2026-03-10 02:21:59.778254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a804b28244c2'
down_revision: Union[str, Sequence[str], None] = 'cb0b221078ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pay_frequency', sa.String(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'effective_from', name='uq_member_salary_effective_from')
    )
    op.create_index(op.f('ix_staff_salaries_id'), 'staff_salaries', ['id'], unique=False)
    op.drop_index(op.f('ix_teacher_salaries_id'), table_name='teacher_salaries')
    op.drop_table('teacher_salaries')
    op.alter_column('organization_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('salary_payments', sa.Column('member_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_teacher_salary_month'), 'salary_payments', type_='unique')
    op.create_unique_constraint('uq_member_salary_month', 'salary_payments', ['member_id', 'month', 'year'])
    op.drop_constraint(op.f('salary_payments_teacher_member_id_fkey'), 'salary_payments', type_='foreignkey')
    op.create_foreign_key(None, 'salary_payments', 'staff_salaries', ['salary_id'], ['id'])
    op.create_foreign_key(None, 'salary_payments', 'organization_members', ['member_id'], ['id'])
    op.drop_column('salary_payments', 'teacher_member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_payments', sa.Column('teacher_member_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'salary_payments', type_='foreignkey')
    op.drop_constraint(None, 'salary_payments', type_='foreignkey')
    op.create_foreign_key(op.f('salary_payments_teacher_member_id_fkey'), 'salary_payments', 'organization_members', ['teacher_member_id'], ['id'])
    op.drop_constraint('uq_member_salary_month', 'salary_payments', type_='unique')
    op.create_unique_constraint(op.f('uq_teacher_salary_month'), 'salary_payments', ['teacher_member_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
    op.drop_column('salary_payments', 'member_id')
    op.alter_column('organization_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('teacher_salaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('pay_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('teacher_salaries_organization_id_fkey')),
    sa.ForeignKeyConstraint(['teacher_member_id'], ['organization_members.id'], name=op.f('teacher_salaries_teacher_member_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('teacher_salaries_pkey')),
    sa.UniqueConstraint('teacher_member_id', 'effective_from', name=op.f('uq_teacher_salary_effective_from'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_teacher_salaries_id'), 'teacher_salaries', ['id'], unique=False)
    op.drop_index(op.f('ix_staff_salaries_id'), table_name='staff_salaries')
    op.drop_table('staff_salaries')
    # ### end Alembic commands ###
