"""update student model

Revision ID: c52abd3d09e8
Revises: 8fa70ad79e59
Create Date: 2026-02-28 17:55:24.202269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c52abd3d09e8'
down_revision: Union[str, Sequence[str], None] = '8fa70ad79e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('students_class_id_fkey'), 'students', type_='foreignkey')
    op.drop_column('students', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('students_class_id_fkey'), 'students', 'classrooms', ['class_id'], ['id'])
    # ### end Alembic commands ###
