"""update exam tables

Revision ID: c8e926007437
Revises: 5c4df91298bd
Create Date: 2026-03-04 10:14:13.965242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e926007437'
down_revision: Union[str, Sequence[str], None] = '5c4df91298bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year_id', 'name', name='uq_term_name_year')
    )
    op.create_index(op.f('ix_terms_id'), 'terms', ['id'], unique=False)
    op.create_index(op.f('ix_exam_papers_id'), 'exam_papers', ['id'], unique=False)
    op.add_column('exam_results', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exam_results_id'), 'exam_results', ['id'], unique=False)
    op.create_foreign_key(None, 'exam_results', 'classrooms', ['classroom_id'], ['id'])
    op.add_column('exams', sa.Column('weightage', sa.Float(), nullable=True))
    op.add_column('exams', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('exams', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('exams', sa.Column('term_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'exams', 'terms', ['term_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'term_id')
    op.drop_column('exams', 'is_locked')
    op.drop_column('exams', 'is_published')
    op.drop_column('exams', 'weightage')
    op.drop_constraint(None, 'exam_results', type_='foreignkey')
    op.drop_index(op.f('ix_exam_results_id'), table_name='exam_results')
    op.drop_column('exam_results', 'classroom_id')
    op.drop_index(op.f('ix_exam_papers_id'), table_name='exam_papers')
    op.drop_index(op.f('ix_terms_id'), table_name='terms')
    op.drop_table('terms')
    # ### end Alembic commands ###
