"""update exam tables

Revision ID: e2eeeb0237df
Revises: c8e926007437
Create Date: 2026-03-04 10:35:14.465673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2eeeb0237df'
down_revision: Union[str, Sequence[str], None] = 'c8e926007437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_percentage', sa.Float(), nullable=False),
    sa.Column('max_percentage', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_result_student', 'exam_results', ['student_id'], unique=False)
    op.alter_column('exams', 'weightage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('uq_term_name_year'), 'terms', type_='unique')
    op.create_unique_constraint(None, 'terms', ['academic_year_id', 'name', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terms', type_='unique')
    op.create_unique_constraint(op.f('uq_term_name_year'), 'terms', ['academic_year_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('exams', 'weightage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index('idx_exam_result_student', table_name='exam_results')
    op.drop_table('grade_scales')
    # ### end Alembic commands ###
